# ===== BEGIN render.yaml =====
services:
  - type: web
    name: nil-wire            # you can change this name if you like
    env: docker
    plan: free                # Render’s free tier is enough
    dockerfilePath: Dockerfile
    envVars:
      - key: OPENAI_API_KEY   # optional—leave blank for excerpt fallback
        sync: false           # keep it secret; not stored in repo
# ====== END render.yaml ======
